- name: Copy Prometheus Configuration
  ansible.builtin.template:
    src: "{{item}}"
    dest: /opt/prometheus/{{item}}
  loop:
    - prometheus.yml
    - record-rules.yml
    - alert-rules.yml

- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Wait for Prometheus Service to Start
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: 9090
    delay: 10
    timeout: 30

- name: Copy Alert Manager configuration
  ansible.builtin.template:
    dest: /opt/alertmanager/alertmanager.yml
    src: alertmanager.yml

- name: Restart Prometheus
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted

- name: Wait for Alertmanager Service to Start
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: 9090
    delay: 10
    timeout: 30
